Controllers/CoursesController.cs
using MVC.DbDal;
using MVC.Models;
using MVC.ModelView;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class CoursesController : Controller
    {
        
        private Dal db = new Dal();
        public ActionResult Index()
        {
            return View(db.Courses.ToList());
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create([Bind (Include = "CourseId,CourseName,Day,Hour,Finish,Class")]Course course)
        {
            Dal dal = new Dal();
            string tempCN = course.CourseName;
            string tempD = course.Day;
            string tempH = course.Hour;
            string tempC = course.Class;
            string tempF = course.Finish;

            List<Course> objCourses = dal.Courses.ToList();
            CourseViewModel cvm = new CourseViewModel();
            cvm.Course = course;
            TimeSpan Tfin;
            TimeSpan Tsta;
            Tfin = TimeSpan.Parse(tempF);
            Tsta = TimeSpan.Parse(tempH);
            TimeSpan TfinExistCourse;
            if (Tfin < Tsta)
            {
                ViewBag.error = "class cannot finish before start";
                return View(cvm);
            }

            foreach (Course x in objCourses)
            {
                    TfinExistCourse = TimeSpan.Parse(x.Finish);
                    if (x.CourseName != tempCN && x.Day == tempD && TfinExistCourse > Tsta && x.Class == tempC)
                {
                    ViewBag.error = "Class Taken,Choose other.";
                    return View(cvm);
                }
                else
                    if (x.CourseName == tempCN && x.Day == tempD && x.Hour == tempH && x.Class == tempC)
                {
                    ViewBag.error = "Course already exist";
                    return View(cvm);
                }
            }

            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cvm);
        }
        public ActionResult Edit(int courseId)
        {
            Course course = db.Courses.Find(courseId);
            return View(course);
        }

        [HttpPost, ActionName("Edit")]
        public ActionResult Edit([Bind(Include = "CourseId,CourseName,Day,Hour,Finish,Class")] Course course)
        {
            Dal dal = new Dal();
            string tempCN = course.CourseName;
            string tempD = course.Day;
            string tempH = course.Hour;
            string tempC = course.Class;
            List<Course> objCourses = dal.Courses.ToList();
            string tempF = course.Finish;
            TimeSpan Tfin;
            TimeSpan Tsta;
            TimeSpan TfinExistCourse;
            Tfin = TimeSpan.Parse(tempF);
            Tsta = TimeSpan.Parse(tempH);
            if (Tfin < Tsta)
            {
                ViewBag.error = "class cannot finish before start";
                return View(course);
            }
            foreach (Course x in objCourses)
            {
                TfinExistCourse = TimeSpan.Parse(x.Finish);
                if (x.Day == tempD && TfinExistCourse > Tsta && x.Class == tempC)
                {
                    ViewBag.error = "Class Taken,Choose other.";
                    return View(course);
                }
                    if (ModelState.IsValid)
                    {
                        db.Entry(course).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                return View(course);
            }

        public ActionResult Delete(int courseId)
        {
            Course course = db.Courses.Find(courseId);
            return View(course);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int courseId)
        {
            Course course = db.Courses.Find(courseId);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult AssignLecturer()
        {
            Dal dal = new Dal();
            List<User> objUsers = dal.Users.ToList<User>();
            List<Course> objCourse = dal.Courses.ToList<Course>();
            LecturerViewModel lvm = new LecturerViewModel();
            lvm.Courses = objCourse;
            lvm.Users = objUsers;
            return View(lvm);
        }
        
        public ActionResult AssignConfirmLecturer()
        {
            return View();
        }   
        [HttpPost]
        public ActionResult AssignConfirmLecturer([Bind(Include = "lecIndex,LecId,LecName,CourseId")] Lecturer lecturer)
        {
            Dal dal = new Dal();
            int tempLecindex = lecturer.lecIndex;
            string tempLecId = lecturer.LecId;
            string tempLn = lecturer.LecName;
            int tempCId = lecturer.CourseId;
            List<Lecturer> objLecturer = dal.Lecturers.ToList();
            List<Course> objCourses = dal.Courses.ToList();
            LecturerViewModel lvm = new LecturerViewModel();
            lvm.Lecturers = objLecturer;
            bool flag = true;


            foreach (Lecturer x in objLecturer)
            {
                if (x.LecId == tempLecId)
                {

                    if (x.CourseId == tempCId)
                    {
                        flag = false;
                        ViewBag.error = "Lecturer already assigned to this course.";
                        return View(lvm);
                    }
                    else
                        if (x.CourseId != tempCId)
                    {
                        Course course = db.Courses.Find(tempCId);
                        if (course != null)
                        {
                            foreach (Course c in objCourses)
                            {
                                TimeSpan Tfin;
                                TimeSpan Tsta;
                                Tfin = TimeSpan.Parse(c.Finish);
                                Tsta = TimeSpan.Parse(course.Hour);
                                if (course.Day == c.Day && Tsta < Tfin && c.CourseId != tempCId)
                                {
                                    flag = false;
                                    ViewBag.error = "Lecturer is busy in this time";
                                    return View(lvm);
                                }
                            }
                        }
                        else
                        {
                            ViewBag.error = "course not exist";
                            return View(lvm);
                        }
                    }
                }
                else
                    if(x.CourseId == tempCId)
                {
                    flag = false;
                    ViewBag.error = "course already lecturerd by other lecturer";
                    return View(lvm);
                }
            }
                if (flag)
                {
                    if (ModelState.IsValid)
                    {
                        db.Lecturers.Add(lecturer);
                        db.SaveChanges();
                        return RedirectToAction("AssignLecturer");
                    }
                }

            ViewBag.error = "Lecturer id not exist in the system";
            return View(lvm);
        }

        public ActionResult AssignStudent()
        {
            Dal dal = new Dal();
            List<User> objUsers = dal.Users.ToList<User>();
            List<Course> objCourse = dal.Courses.ToList<Course>();
            List<Student> objStudent = dal.Students.ToList<Student>();
            CourseViewModel cvm = new CourseViewModel();
            cvm.Courses = objCourse;
            cvm.Students = objStudent;
            cvm.Users = objUsers;
            
            return View(cvm);
        }
        public ActionResult AssignConfirm()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AssignConfirm([Bind(Include = "studIndex,StudId,StudName,CourseId")] Student student)
        {

            Dal dal = new Dal();
            int tempStudindex = student.studIndex;
            string tempStudId = student.StudId;
            string tempSn = student.StudName;
            int tempCId = student.CourseId;

            List<Student> objStudents = dal.Students.ToList();
            List<Course> objCourses = dal.Courses.ToList();
            CourseViewModel cvm = new CourseViewModel();
            cvm.Students = objStudents;
            bool flag = false;
            foreach (Student x in objStudents)
            {
                if (x.StudId == tempStudId)
                {
                    flag = true;
                    if (x.CourseId == tempCId)
                    {
                        flag = false;
                        ViewBag.error = "Student already assigned to this course.";
                        return View(cvm);
                    }
                    else
                        if (x.CourseId != tempCId)
                    {
                        Course course = db.Courses.Find(tempCId);
                        if (course != null)
                        {
                            foreach (Course c in objCourses)
                            {
                                TimeSpan Tfin;
                                TimeSpan Tsta;

Controllers/LoginController.cs
using MVC.Models;
using MVC.ModelView;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.DbDal;
namespace MVC.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View("LoginPage");
        }
        public ActionResult LoginPage()
        {
            UserViewModel cvm = new UserViewModel();
            User objUser = new User();
            Dal dal = new Dal();
            List<User> objUsers = dal.Users.ToList();

            if (Request.Form.Count > 0)
            {
                objUser.Id = Request.Form["User.Id"].ToString();
                objUser.Password = Request.Form["User.Password"].ToString();

                foreach (User x in objUsers)//to make sure the username is valid
                {
                    if (x.Id == objUser.Id && x.Password == objUser.Password)
                    {
                        cvm.User = x;//add the current user to the CVM user
                        Session["currUserId"] = x.Id;
                        Session["currUserType"] = x.Type;
                        Session["currName"] = x.Name;
                        HomeViewModel hvm = new HomeViewModel();
                        return View("homePage", hvm);
                    }
                }
                cvm.User = new User();
                ViewBag.UserORPassError = "Id or Password incorrect! please try again";
                return View("LoginPage", cvm);//Id Or Pass not found
            }
            return View("LoginPage");
        }

        public ActionResult Logout()
        {
          
            Session["currUserId"] = null;//clean session items
            Session["currUserType"] = null;


            UserViewModel cvm = new UserViewModel();
            cvm.User = new User();//clean curr user

            return View("LoginPage", cvm);//username Or Pass not found
        }
    }
}

Views/Shared/FloatingHeader.cshtml
<!DOCTYPE html>
<html>
<head>
    <style>
        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #017c00;
        }

        li {
            float: left;
            border-right: 1px solid #bbb;
        }

            li:last-child {
                border-right: none;
            }

            li a {
                display: block;
                color: white;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }

                li a:hover:not(.active) {
                    background-color: #01bd00;
                }

        .active {
            background-color: #01bd00;
        }
        #responsive-image {  width: 100%;  height: 80px; } 
    </style>
</head>
<body>
    <div>
        <center><img src="../../images/sce.jpg" alt="sce" id="responsive-image"> </center>
        
        <ul>
            @{
                if (@Session["currUserId"] != null)
                {
                    if (@Session["currUserType"].ToString() == "Admin")//if the current user is a Admin -> Open all the Option for him.
                    {
                            <li><a href="@Url.Action("homePage", "Home")"> Home</a></li>
                            <li><a href="@Url.Action("Index", "Courses")"> Courses Management</a></li>
                            <li><a href="@Url.Action("AssignStudent", "Courses")">Assign Student To Course</a></li>
                            <li><a href="@Url.Action("AssignLecturer", "Courses")">Assign Lecturer To Course</a></li>
                            <li><a href="@Url.Action("CreateExam", "Courses")">Create Exam</a></li>
                            <li><a href="@Url.Action("EditExam", "Courses")">Edit Exam Schedule</a></li>
                            <li><a href="@Url.Action("EditExamGrade", "Courses")">Edit Exam Grades</a></li>
                            <li><a href="@Url.Action("Logout", "Login")">Logout</a></li>
                            <li><a style="color:darkgrey">  Welcome Back @Session["currName"]!</a></li>

                    }
                    else if (@Session["currUserType"].ToString() == "Student")
                    {
                        <li><a href="@Url.Action("homePage", "Home")"> Home</a></li>
                        <li><a href="@Url.Action("ShowSchedule", "Student")">View Schedule</a></li>
                        <li><a href="@Url.Action("ShowExam", "Student")">View Exams</a></li>
                        <li><a href="@Url.Action("Logout", "Login")">Logout</a></li>
                        <li><a style="color:darkgrey">  Welcome Back @Session["currName"]!</a></li>
                    }
                    else if (@Session["currUserType"].ToString() == "Lecturer")
                    {
                        <li><a href="@Url.Action("homePage", "Home")"> Home</a></li>
                        <li><a href="@Url.Action("ShowSchedule", "Lecturer")">View Schedule</a></li>
                        <li><a href="@Url.Action("EditExamGradeLec", "Lecturer")">Show Exams</a></li>
                        <li><a href="@Url.Action("Logout", "Login")">Logout</a></li>
                        <li><a style="color:darkgrey">  Welcome Back @Session["currName"]!</a></li>
                    }
                }
                else//if nobody is login ->show only the login option
                {
                    < li >< a href = "@Url.Action("Login", "Login")" > Login </ a ></ li >
                }
            }

        </ul>

    </div>
</body>
</html>
@RenderBody()

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/homePage.cshtml
@model MVC.ModelView.HomeViewModel
@using MVC.Models
@{
    Layout = "~/Views/Shared/FloatingHeader.cshtml";
}

<!DOCTYPE html>
<html>
<style>
    html {
        background-image: url('../../images/backgroundwhite.jpg');
        background-size: cover;
    }
</style>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>SCE Management System</title>
</head>
<body>

</body>

</html>